name: Build and Commit MCPack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create MCPack archive
        run: |
          mkdir -p nebula
          unzip output/nebula.mcpack -d nebula/

      - name: Commit MCPack file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [ -d nebula ]; then
            git add nebula/
            git commit -m "Auto-build: Bedwars Mega MCPack updated" || echo "No changes to commit"
            git push
          else
            echo "No .mcpack file generated."
          fi
