name: Build and Commit MCPack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        run: |
          echo "=== List project files ==="
          ls -R .

          echo "=== Check target directory ==="
          ls -R temp_unpack || echo "temp_unpack not found"
          ls -R temp_unpack/file9_work || echo "file9_work not found"

      - name: Prepare and unzip
        run: |
          mkdir -p nebu

          ZIP="temp_unpack/file9_work/SpearsOfMayhem_RP.zip"

          if [ ! -f "$ZIP" ]; then
            echo "Error: ZIP not found -> $ZIP"
            exit 1
          fi

          unzip "$ZIP" -d nebu/

      - name: Commit MCPack file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add nebu/
          git commit -m "Auto-build: Bedwars Mega MCPack updated" || echo "No changes to commit"
          git push
