name: Move Item Textures

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  move_textures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Move Pack/textures/item to items
        run: |
          mkdir -p Pack/textures/block
          if [ -d "blocks" ]; then
            mv Pack/textures/block/* Pack/textures/blocks || true
            rm -rf items
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Move item textures from Pack/textures/item to items" || echo "No changes to commit"
          git pull
          git push
